import {readFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import vm from 'node:vm';
const {PGlite}=await import(process.env.PGLITE_MODULE ?? '@electric-sql/pglite');
const db=new PGlite();
await db.exec(`create role anon;create role authenticated;create schema auth;create schema private;
create table auth.users(id uuid primary key,deleted_at timestamptz,is_anonymous boolean default false,banned_until timestamptz);
create table auth.sessions(id uuid primary key,user_id uuid,not_after timestamptz);
create function auth.uid() returns uuid language sql stable as $$select (current_setting('request.jwt.claims',true)::jsonb->>'sub')::uuid$$;
create function auth.jwt() returns jsonb language sql stable as $$select current_setting('request.jwt.claims',true)::jsonb$$;
create table private.account_hub_clients(client_id uuid primary key,enabled boolean);
create function private.account_assert_not_deletion_pending() returns void language plpgsql as $$begin if exists(select 1 from public.account_deletion_requests where user_id=auth.uid() and status in ('pending','deleting')) then raise exception 'pending';end if;end$$;
create table public.account_app_connections(user_id uuid,app_slug text,status text);
create table public.account_app_grants(user_id uuid,app_slug text,permission_id text,status text);
create table public.account_deletion_requests(user_id uuid,status text);
create table public.tms60_sync_state(user_id uuid,translation_id text,revision bigint,state_schema integer,state jsonb,updated_at timestamptz,primary key(user_id,translation_id));
create table public.tms60_backups(id uuid,user_id uuid,state jsonb);
alter table public.tms60_sync_state enable row level security;alter table public.tms60_backups enable row level security;
create policy sync_owner on public.tms60_sync_state for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy backup_owner on public.tms60_backups for all to authenticated using(user_id=auth.uid()) with check(user_id=auth.uid());
grant usage on schema auth,public to authenticated;grant select,insert,update,delete on public.tms60_sync_state,public.tms60_backups to authenticated;
create function public.restore_thiepn_tms60_backup(uuid) returns jsonb language sql security definer as $$select '{"restored":true}'::jsonb$$;
`);
await db.exec(await readFile(new URL('../../supabase/migrations/20261003221217_hub_h15_tms60_projection.sql',import.meta.url),'utf8'));
const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',C='33333333-3333-4333-8333-333333333333',S='44444444-4444-4444-8444-444444444444',R='55555555-5555-4555-8555-555555555555';
await db.query('insert into auth.users(id) values($1),($2)',[A,B]);await db.query('insert into auth.sessions(id,user_id) values($1,$2)',[S,A]);
await db.query('insert into private.account_hub_clients values($1,true)',[C]);
await db.query("insert into public.account_app_connections values($1,'tms60','connected')",[A]);
await db.query("insert into public.account_app_grants values($1,'tms60','app_data.read','granted')",[A]);
const claims=(managed=true,owner=A)=>({sub:owner,aud:'authenticated',role:'authenticated',session_id:S,exp:Math.floor(Date.now()/1000)+3600,...(managed?{client_id:C}:{})});
async function jwt(value){await db.query("select set_config('request.jwt.claims',$1,false)",[JSON.stringify(value)]);}
await jwt(claims(false));
const purposes=['summary','continue','search'].map(op=>'tms60.hub.'+op+'.read');
let consent=(await db.query('select public.set_thiepn_hub_tms60_consent($1,$2,null) value',['esv',purposes])).rows[0].value;
assert.equal(consent.permissions.length,3);
await assert.rejects(db.query('select public.set_thiepn_hub_tms60_consent($1,$2,null)',['esv',purposes]));
await assert.rejects(db.query('select public.set_thiepn_hub_tms60_consent($1,$2,null)',['bad',purposes]));
const now=Date.now();const schedule=(phase='new',due=0,lastReviewed=0)=>({phase,due,lastReviewed});
const state={progress:Object.fromEntries(Array.from({length:60},(_,i)=>[i+1,{stage:0,lastReviewed:0,wording:schedule(),reference:schedule()}])),events:[{answer:'PRIVATE ANSWER'}],customs:['PRIVATE TEXT']};
Object.assign(state.progress[1],{stage:6,lastReviewed:now-1000,wording:schedule('review',now-1000,now-2000),reference:schedule('review',now-1000,now-1000)});
Object.assign(state.progress[2],{stage:2,lastReviewed:now-2000,wording:schedule('learning',now-1000)});
Object.assign(state.progress[3],{stage:6,lastReviewed:now-3000,wording:schedule('review',now+86400000),reference:schedule('review',now-1000)});
await db.query('insert into public.tms60_sync_state values($1,$2,1,6,$3,now())',[A,'esv',state]);
await db.query('insert into public.tms60_sync_state values($1,$2,1,6,$3,now())',[B,'esv',{private:'OTHER OWNER'}]);
await db.query('insert into public.tms60_backups values($1,$2,$3)',[R,A,{answer:'PRIVATE BACKUP'}]);
await jwt(claims());
async function read(op='summary',translation='esv',query=null,revision=consent.revision){return (await db.query('select public.read_thiepn_hub_tms60($1,$2,$3,$4,$5) value',[op,revision,translation,R,query])).rows[0].value;}
const app=await readFile(new URL('../../app.html',import.meta.url),'utf8');
const native=vm.runInNewContext(app.match(/^function due.*$/m)[0]+'\n'+app.match(/^function metrics.*$/m)[0]+'\nmetrics()', {state,VERSES:Array.from({length:60},(_,i)=>({id:i+1})),now:()=>now,DAY:86400000,isWordingStable:()=>false,isReferenceKnown:()=>false});
let envelope=await read();assert.equal(envelope.data.dueTaskCount,native.dueW+native.dueR);assert.equal(envelope.data.newVerseCount,native.unseen);assert.deepEqual([envelope.data.dueTaskCount,envelope.data.dueVerseCount,envelope.data.newVerseCount],[3,2,57]);assert.equal(envelope.data.items.length,3);
assert.doesNotMatch(JSON.stringify(envelope),/PRIVATE|answer|customs|state_schema|progress/);
let continued=await read('continue');assert.equal(continued.data.items[0].resourceId,'esv:1:reference');assert.equal(continued.data.items[1].dimension,'learning');
assert.equal((await read('search','esv','2 Corinthians')).data.items[0].title,'2 Corinthians 5:17');
assert.equal((await read('search','esv','%')).status,'empty');
await assert.rejects(read('summary','niv'));await assert.rejects(read('search','esv',''));await assert.rejects(read('summary','esv','query'));
await db.exec('set role authenticated');assert.deepEqual((await db.query('select * from public.tms60_sync_state')).rows,[]);assert.deepEqual((await db.query('select * from public.tms60_backups')).rows,[]);await assert.rejects(db.query('select public.restore_thiepn_tms60_backup($1)',[R]));await db.exec('reset role');
await jwt(claims(false));assert.equal((await db.query('select public.restore_thiepn_tms60_backup($1) value',[R])).rows[0].value.restored,true);
await db.exec('set role authenticated');assert.equal((await db.query('select * from public.tms60_sync_state')).rows.length,1);await db.exec('reset role');
await db.query('select public.set_thiepn_hub_tms60_consent($1,$2,null)',['niv',purposes]);await jwt(claims());await assert.rejects(read('summary','niv',null,consent.revision));
await jwt(claims(false));const niv=(await db.query('select public.get_thiepn_hub_tms60_consent($1) value',['niv'])).rows[0].value;await jwt(claims());assert.equal((await read('summary','niv',null,niv.revision)).status,'unconnected');
await db.query('update public.tms60_sync_state set state_schema=7 where user_id=$1',[A]);assert.equal((await read()).status,'unsupported');await db.query('update public.tms60_sync_state set state_schema=6 where user_id=$1',[A]);
await jwt(claims(true,B));await assert.rejects(read());await jwt({...claims(),client_id:R});await assert.rejects(read());await jwt({...claims(),session_id:R});await assert.rejects(read());await jwt({...claims(),exp:1});await assert.rejects(read());await jwt(claims());
await db.query("update public.account_app_connections set status='disconnected' where user_id=$1",[A]);await assert.rejects(read());await db.query("update public.account_app_connections set status='connected' where user_id=$1",[A]);await assert.rejects(read());
await jwt(claims(false));let latest=(await db.query('select public.get_thiepn_hub_tms60_consent($1) value',['esv'])).rows[0].value;assert.deepEqual(latest.permissions,[]);assert.notEqual(latest.revision,consent.revision);
consent=(await db.query('select public.set_thiepn_hub_tms60_consent($1,$2,$3) value',['esv',purposes,latest.revision])).rows[0].value;await jwt(claims());
await db.query('delete from private.account_hub_tms60_budget where user_id=$1',[A]);for(let i=0;i<60;i++)await read();await assert.rejects(read());
await db.close();console.log('H15 owner SQL: consent, native counts, translation isolation, metadata bounds, first-party restore, OAuth raw denial, session rejection, permanent revocation and rate limit passed.');
